### ISSUE TITLE
Make it installable

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#24]

**Comment by luisherranz** [comment]
@rmartinezduque could you please let me know what needs to be done in iOS to make this work?

In Android it's already working.

**Comment by rmartinezduque** [comment]
@luisherranz here's the documentation:

https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by luisherranz** [comment]
Thanks @reyes. We'll add those iOS metas 👍
