### ISSUE TITLE
Swap FA pro icons

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#30]
Blocked until the design-team tells us what icons to use.

**Comment by lucijanblagonic** [comment]
@luisherranz do we know which icons are pro? I was thinking we could switch those only perhaps.

**Comment by luisherranz** [comment]
You can check them in their page. For example, `utensils` is free but the outlined one you used is not:
https://fontawesome.com/icons?d=gallery&q=utensils

**Comment by lucijanblagonic** [comment]
Ok. Let's make our life easier and just use the free alternatives.

They won't look as nice but but at least they will look consistent in style.

* utensils
* users
* comments
* bullhorn

They all have the free filled counterparts.

**Comment by luisherranz** [comment]
Ok, we'll use those then. Thanks!

**Comment by luisherranz** [comment]
Reopening to switch back to the original icons now that we have the FA Pro license.
