### ISSUE TITLE
Images of venue and tracks

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#32]
Upload them as featured images in the following WP pages:
- [ ] Venue Map
- [ ] Milky Way Track
- [ ] Andromeda Track
- [ ] Hayabusa
- [ ] Cassini
- [ ] Rosetta

Please take into account that the cache of the PWA refreshes after 3-6 minutes. If you want to bypass the cache, load the PWA using this url:
https://app.wp-europe.org/?server=https://origin-pwa-v1.frontity.io

**Comment by lucijanblagonic** [comment]
@luisherranz 
1) Do we have a size limitation?
2) Do you suggest we add them without numbers?

**Comment by luisherranz** [comment]
> Do we have a size limitation?

No, no problem. WP will crop it and we'll use those sizes to populate the `srcset` field.

> Do you suggest we add them without numbers?

Don't know, sorry :)

If you want you can upload different versions here so people can give their opinion.

**Comment by ePascalC** [comment]
I have uploaded the png files and changed the featured images for the 2 tracks and 3 workshops.
Not sure if I need to change the venue map or not ... but I uploaded the full map also into the media library

**Comment by ePascalC** [comment]
Now also changed the venue map (the new one has colors)

**Comment by luisherranz** [comment]
Thanks @ePascalC!
