### ISSUE TITLE
Announcements refresh button

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#33]
This was not included in the wirefrimes, sorry about that.

This is the behaviour:
![](https://media.giphy.com/media/fxw6NVwKTXjqOIOjjR/giphy.gif)

**Comment by lucijanblagonic** [comment]
![announcements refreshed](https://user-images.githubusercontent.com/773721/40727023-440339b4-6427-11e8-83c6-69e884ea9df8.png)
![announcements single](https://user-images.githubusercontent.com/773721/40727024-449a2cf2-6427-11e8-9f20-884f120ebf8b.png)

Added examples here. Uploading on Drive.

**Comment by luisherranz** [comment]
Closed via https://github.com/frontity/wordcamp-theme/commit/a98009df782891ed0441bf11301be39e32c3bf43.
