### ISSUE TITLE
Desktop view (WP Theme)

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#35]
This is for the WP theme.

Something like this:
![artboard](https://user-images.githubusercontent.com/3305402/40482397-32cc41aa-5f44-11e8-9aba-e0089b2c77bc.jpg)

**Comment by lucijanblagonic** [comment]
![desktop welcome](https://user-images.githubusercontent.com/773721/40726962-2108c2bc-6427-11e8-9031-5cfdac83d7dc.png)

Same as other desktop screens. I'll check the content with #communication-teams.

**Comment by luisherranz** [comment]
Is the grey rectangle space for the QR?

**Comment by lucijanblagonic** [comment]
Yes. The one you generated is looking good :)

**Comment by DAreRodz** [comment]
Closed at https://github.com/frontity/wordcamp-wp-theme/commit/b0852b785126f4a272177d11b86876e547428641.
