### ISSUE TITLE
Content for the "in-between" pages

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#37]
Enter the content in the following WP pages:
- [x] Before the event (view in "On Now" with `setTime(14,7,0)`)
- [x] Contributor Day (view in "On Now" with `setTime(14,9,0)`)
- [x] Thursday night (view in "On Now" with `setTime(14,19,0)`)
- [x] Friday night (view in "On Now" with `setTime(15,19,0)`)
- [x] After party (view in "On Now" with `setTime(16,20,0)`)
- [x] After the event (view in "On Now" with `setTime(17,3,0)`)

Please take into account that the cache of the PWA refreshes after 3-6 minutes. If you want to bypass the cache, load the PWA using this url:
https://app.wp-europe.org/?server=https://origin-pwa-v1.frontity.io

**Comment by ePascalC** [comment]
That link for the cache bypass does not seem to work ...

For the pages, I have put temporary text, all to be reviewed by the communication-team!

**Comment by luisherranz** [comment]
> That link for the cache bypass does not seem to work

Sorry, we changed the domain. It's updated now:
https://app.wp-europe.org/?server=https://origin-pwa-v1.frontity.io
