### ISSUE TITLE
PWA failed loading (WP Theme)

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#38]
This is for the WP theme.

Something like this:
![artboard](https://user-images.githubusercontent.com/3305402/40488361-1fa4db98-5f56-11e8-9bfb-581838aa5157.jpg)

**Comment by lucijanblagonic** [comment]
![desktop error](https://user-images.githubusercontent.com/773721/40726694-8cb72e82-6426-11e8-8bec-6582fe71ae85.png)

The same layout as not supported, only different text.

**Comment by luisherranz** [comment]
@lucijanblagonic why did you tag the communications-team here? Did they need to review the text?

**Comment by luisherranz** [comment]
I'm removing them for now. Feel free to answer and tag them back if needed.

**Comment by DAreRodz** [comment]
Closed at https://github.com/frontity/wordcamp-wp-theme/commit/b0852b785126f4a272177d11b86876e547428641.
