### ISSUE TITLE
Content for the credits page

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#39]
Enter the content in the "Credits" WP page.

Please take into account that the cache of the PWA refreshes after 3-6 minutes. If you want to bypass the cache, load the PWA using this url:
https://app.wp-europe.org/?server=https://preorigin.wp-pwa.com

**Comment by jennybeaumont** [comment]
I'm sorry, but we need to delete the credits page. This is not conform with WordCamp Europe practice and policy. No individual credits can be displayed anywhere on the app. thnx!

**Comment by luisherranz** [comment]
No problem. Closing this!
