### ISSUE TITLE
2 or 3 announcements posts

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#40]
It'd be great if you could add 2 or 3 posts before the PWA announcement so people taking a look at the PWA don't see that section empty.

Once they are created, you can delete the test ones (_Announcement_ 1 and _Really long title of the Announcement 2 with more text_)

Announcement posts are regular posts. No special category needed.

**Comment by ePascalC** [comment]
Please check https://github.com/frontity/wordcamp-theme/issues/58
How to add a picture?

**Comment by luisherranz** [comment]
#58 is solved now 👍

**Comment by luisherranz** [comment]
Thanks @ePascalC. Closing this now but feel free to add more content whenever you want.
