### ISSUE TITLE
Add content page: Code of Conduct

### ISSUE THREAD

**Issue by jennybeaumont** [frontity/wordcamp-theme#52]
As an attendee I want to be able to easily find information about how to reach the response team so that I can report a code of conduct violation.

As a WCEU org, I want attendees to have the CoC in mind when they view the app so that they are always conscious and mindful of their behavior.

**Comment by luisherranz** [comment]
Ok. I'll tag the `dev-team` first to add this to the PWA Menu. Once we've added that page, I'll tag the `communication-team` so they can edit the content in WP.

**Comment by ePascalC** [comment]
Full version and form (so a link to this page from the app): https://2018.europe.wordcamp.org/code-of-conduct/

To be decided if we need a much shorter version on the app and then of course linking to the full version and the form

**Comment by DAreRodz** [comment]
Added the page to the PWA Menu at 53e3412cfca668c507827735e5bb599351a4b6c3. Waiting for it to be put into production before tagging the `communication-team`.

**Comment by ePascalC** [comment]
Basic text added to the page. To be reviewed by communication-team

**Comment by jennybeaumont** [comment]
Here is the full text for the page:

WordCamp Europe believes our community should be truly open for everyone. As such, we are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, disability, age, ethnicity, religion, preferred operating system, programming language, or text editor.

How to treat each other:

- Be considerate, respectful, and collaborative.
- Be inclusive and value each other’s ideas, styles and viewpoints.
- Be mindful of your surroundings and of other participants. Help new perspectives be heard.
- Participate in an authentic and active way. Lead by example and match your actions with your words.

The following will not be tolerated at WordCamp Europe:

- Violence and threats of violence
- Personal attacks
- Derogatory language
- Unwelcome sexual attention, unwelcome physical contact or disruptive behaviour
- Encouraging or promoting unacceptable behaviour

Are you seeing behaviour that doesn’t respect these guidelines? Our Response team is here to help:

Email: conduct@wp-europe.org
Phone/SMS: +381 62 107 98 92
Or use our anonymous form:
https://2018.europe.wordcamp.org/code-of-conduct/

**Comment by jennybeaumont** [comment]
I've added the text to the wp admin, but it doesn't display on the site. Can we please push out the new menu and content? What is the procedure for that?

**Comment by luisherranz** [comment]
It's in production now so closing this.
