### ISSUE TITLE
Add content page: menus

### ISSUE THREAD

**Issue by jennybeaumont** [frontity/wordcamp-theme#53]
As an attendee I'd like easy to access to the lunch menus and After Party dinner menu so that I can decide whether or not to eat elsewhere.

**Comment by luisherranz** [comment]
Ok. I'll tag the `dev-team` first to add this to the PWA Menu. Once we've added that page, I'll tag the `communication-team` so they can edit the content in WP.

**Comment by DAreRodz** [comment]
Added the page to the PWA Menu at 53e3412cfca668c507827735e5bb599351a4b6c3. Waiting for it to be put into production before tagging the `communication-team`.

**Comment by luisherranz** [comment]
It's in production now so tagging the `communication-team`.

**Comment by rmartinezduque** [comment]
Please remember to add some content in "Menus" as this page is still empty. Thanks!

- [ ] Lunch menus
- [ ] After Party dinner menu

**Comment by ePascalC** [comment]
I have entered the menu of Day 1. Before I do Day 2 and the afterparty, can we agree on the styling?

On the original post I have centered everything (https://app.wp-europe.org/wp-admin/post.php?post=78&action=edit) but inside the app that styling is removed.

@lucijanblagonic and @mburridge can you please give your input so I can complete the other days?

**Comment by ePascalC** [comment]
Input received, thanks. Updating the menus in some hours.

**Comment by ePascalC** [comment]
All done.
