### ISSUE TITLE
Facebook, twitter and Website in Menu

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#57]
In the menu there is a link to the Facebook page of WCEU and below that to the twitter account.

1) The link to the site should also be in that list:  https://2018.europe.wordcamp.org/
2) It might be better to just have icons next to each other on 1 line to save space in the menu with all 3 (website, facebook, twitter)

**Comment by luisherranz** [comment]
Well thought. 

For the design team: please once this design is ready, remove your tag and add ours (`dev-team`).

**Comment by ePascalC** [comment]
Almost forgot: we also have Instagram! https://www.instagram.com/wceurope/

**Comment by lucijanblagonic** [comment]
![menu](https://user-images.githubusercontent.com/773721/40727152-952d7ed0-6427-11e8-9825-ad3b16217696.png)

Updated.

**Comment by ePascalC** [comment]
@luisherranz Do you have these icons? Or do you have similar ones?

**Comment by luisherranz** [comment]
@ePascalC we've finally purchased FontAwesome Pro so no problem anymore :)
