### ISSUE TITLE
Announcements page goes over NavBar (z-index problem)

### ISSUE THREAD

**Issue by mburridge** [frontity/wordcamp-theme#59]
On iOS the content of the Announcements page scrolls over and obscures the title bar.

**Comment by ePascalC** [comment]
I confirm the same bug on Android.

**Comment by luisherranz** [comment]
It looks like we forgot to open (and close) an issue about this but it has already been solved. I'll be on production today.

**Comment by luisherranz** [comment]
My bad, this is still not solved. Reopening.
