### ISSUE TITLE
Announcements counter

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#63]
When I'm not on the app and an announcement is sent, I will not receive the push notification (correct me if I'm wrong!).
If I enter the app later, there is no visual indication that there is a new announcement. Would be nice to have an indication somehow.
![capture](https://user-images.githubusercontent.com/18325208/40719117-ac065d08-6412-11e8-923a-929b0f614564.PNG)

**Comment by luisherranz** [comment]
> When I'm not on the app and an announcement is sent, I will not receive the push notification (correct me if I'm wrong!).

Yes, users will receive a push notification even if the app is closed and their phone locked :)

But apart from that fact, we could add a "X new" badge in the menu. Then mark them as readed if the users actually goes to the "Announcements" section.
![group](https://user-images.githubusercontent.com/3305402/40719269-5c390676-6413-11e8-9710-b324e4fa65c5.png)

**Comment by luisherranz** [comment]
Maybe we could add a bubble to the menu icon as well:

![schedule now](https://user-images.githubusercontent.com/3305402/40831293-e9b87628-6588-11e8-8417-495ea3ea1ac2.png)

**Comment by ePascalC** [comment]
Yes please !

**Comment by lucijanblagonic** [comment]
Completely agree. I wouldn't add the "new" item though as the number is sufficient (and widely used). With one more addition — I would mark which ones are new when they are fist opened. What do you think?

![announcements refreshed](https://user-images.githubusercontent.com/773721/40999799-48bb7ac2-690c-11e8-97d4-e021eae7f0d1.png)
![menu](https://user-images.githubusercontent.com/773721/40999801-48d6a2ac-690c-11e8-9696-b98ac2d4e1c3.png)
![schedule full favorite](https://user-images.githubusercontent.com/773721/40999810-4e8fea82-690c-11e8-8f4a-9c0c75e49d41.png)

Let me know if this is OK.

**Comment by luisherranz** [comment]
Thanks for the design @lucijanblagonic!

**Comment by luisherranz** [comment]
I think a **Mark all as read** button could be useful here. Maybe between **Refresh** and the first post. What do you think?

cc: @lucijanblagonic, @ePascalC, @mburridge

**Comment by lucijanblagonic** [comment]
Does it make sense to save the person that one click and just clear the notifications when they open the announcements page? We would still show "New" labels but after they see all announcements we would clear it the second time.

**Comment by luisherranz** [comment]
The problem with clearing the notifications when they open the announcements page is that if, for example, they have 3 new notifications and they click on one to read it, then go back to the announcements page to read the other two, the new tags are gone and that may be misleading (which ones were new a moment ago?).

For that reason, we think it'd be better to let them mark everything as read once they've finished  reviewing the announcements.

In the future, we can think about more complex and maybe better UX solutions for this problem, but for now I'd like us to choose between one of these two options ("clear notifications when announcements page is opened" and "mark all as read button") because can add them without too much code right now.

**Comment by lucijanblagonic** [comment]
I'm for clearing the notification when the announcements page is opened. Maybe the "new" tag can fade out or something after 10 sec. I would like to avoid having another button, simply ti keep the UI as simple as possible. That sounds good to you?

**Comment by luisherranz** [comment]
I don't think the fade-out will lead to a good user experience. What about cleaning the notifications when the user abandons the announcement page?

**Comment by luisherranz** [comment]
Ok, wait. We think we found out a way to get it right: clear notifications when user leaves the announcement page but **only if it goes to a page different than an individual announcement**.

That way, when the user goes to **announcements**, the notifications are there. If he/she visits an **individual announcement**, only that announcement is marked as read. When he/she goes back to **announcements**, the remaining notifications are still there. Only when he/she exits announcements completely to go to **schedule** or any other section, all the remaining notifications are cleared.

**Comment by lucijanblagonic** [comment]
Love it.

**Comment by luisherranz** [comment]
@orballo you can close this issue whenever is merged.
