### ISSUE TITLE
Warning in Chrome: Failed to execute 'write' on 'Document'

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#67]
(index):9 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

It does not seem to block anything ...

**Comment by luisherranz** [comment]
I'll look into it. Thanks @ePascalC.

**Comment by luisherranz** [comment]
Solved.
