### ISSUE TITLE
Make CoC phone number clickable

### ISSUE THREAD

**Issue by jennybeaumont** [frontity/wordcamp-theme#69]
As a user, I'd like to be able to click on the phone number on the Code of Conduct page and have it automatically dial so that I don't have to manually type the number in myself.

**Comment by ePascalC** [comment]
@luisherranz , I'm working on that, I can add the href="tel:" in the CoC page to force the phones to recognize the number. Testing now...

**Comment by ePascalC** [comment]
I have added in the CoC page:
`Phone/SMS: <a href="tel:+38162100000">+381 62 100 00 00</a>`

I tested on Android (Samsung browser) and iOS (Safari) and it seems to work. If somebody else could test and confirm?

**Comment by luisherranz** [comment]
Working on Android Chrome. Closing it now. Thanks @ePascalC 👍
