### ISSUE TITLE
No push notifications on iOS

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#75]
As it seems there are no push notifications for iOS, should we hide the 'Push notifications' button when it's iOS?

I think https://github.com/frontity/wordcamp-theme/issues/63 becomes important because of the unavailability of push on iOS

**Comment by luisherranz** [comment]
I think the Push Notifications button is not shown when the device doesn't support it.

@DAreRodz could you please confirm this?

**Comment by DAreRodz** [comment]
Yes, we are currently using the function `isPushNotificationsSupported` from the [OneSignal SDK](https://documentation.onesignal.com/v5.0/docs/web-push-sdk#section--ispushnotificationssupported-) to know if the browser supports push notifications, and thus hide the button in case it does not.
