### ISSUE TITLE
Logo on home page too big

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#79]
Our official logo, displayed on the 'home page' when launching the app is slightly cut to at the right side (both in Chrome on my laptop with Windows as in the Samsung browser on my S5)

When you click 'Up Next' you still see some part of the logo at the left side.

**Comment by luisherranz** [comment]
This was solved in the https://github.com/frontity/wordcamp-theme/issues/77 issue :)

**Comment by luisherranz** [comment]
![screen shot 2018-06-06 at 12 19 13](https://user-images.githubusercontent.com/3305402/41032507-e282673e-6983-11e8-9f7a-3fb584f4d5a2.png)
