### ISSUE TITLE
Close/Menu button strange behaviour

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#85]
When reading annoucements, the close button sometimes show the menu. It is then impossible to close the annoucements. (Samsung browser on S5, but same on desktop with chrome)

**Comment by luisherranz** [comment]
Could you please provide step by step guidance for reproduction?

**Comment by ePascalC** [comment]
The behaviour of the button is different then in the beginning. When I was on Announcements about 1 month ago, there was a 'close', now there is 'Menu'. I now understood that in fact you re-use the menu to switch to the schedule, so I was still thinking of the very first version of the app.

The new behaviour works fine, so we can close this issue.

**Comment by luisherranz** [comment]
Yes, we changed announcements to the complete Menu instead of the close button. I think it was a @mburridge proposal :)
