### ISSUE TITLE
Announcements: remove author (and date?)

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#89]
When annoucements are made, the date and author are currently displayed.

The author is not needed for sure and needs to be removed.

@lucijanblagonic @mburridge how about the date? Should it be there?

**Comment by lucijanblagonic** [comment]
I think we should keep the date, but expand it to time as well (hh:mm). That way you can if it's an old announcement?

**Comment by mburridge** [comment]
Agree, date and time (24hour clock) should be displayed.

**Comment by luisherranz** [comment]
Ok. I'll assign this to the `dev-team` because it looks like it won't need a redesign.
