### ISSUE TITLE
Announcement time incorrect

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#94]
I have published a post (so created an announcement) on June 8 at 23:35 (my local time).
On the site it says it was created June 9 at 01:35.

Please indicate where to change what (website side? app side?)
![image](https://user-images.githubusercontent.com/18325208/41182277-3c681b20-6b75-11e8-9557-982f9b25039b.png)

**Comment by luisherranz** [comment]
It looks like announcements are using the server time (UTC) instead of local time. We'll fix it today.

**Comment by luisherranz** [comment]
@DAreRodz could you please take care of this?

**Comment by DAreRodz** [comment]
Done at https://github.com/wp-pwa/wp-org-connection/commit/9b3d613d9282e5f25656ffa02e16e427d43db530
