### ISSUE TITLE
Venue map: Unclear that swipe shows detailed maps

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#96]
At a certain moment I saw a '> Next' on the main venue map to indicate there were other maps when swiping. Now this seems to have disappeared, so people won't understand how to find the detailed maps.

Related:
https://github.com/frontity/wordcamp-theme/issues/65
https://github.com/frontity/wordcamp-theme/issues/42

**Comment by luisherranz** [comment]
It's also missing in the announcements.
